all adding subtracting multiplying

adding adding.o
	ld adding.o -o adding

adding.o adding.s
	as adding.s -o adding.o

subtracting subtracting.o
	ld subtracting.o -o subtracting

subtracting.o subtracting.s
	as subtracting.s -o subtracting.o

multiplying multiplying.o
	ld multiplying.o -o multiplying

multiplying.o multiplying.s
	as multiplying.s -o multiplying.o
